---
title: "Exercise_2"
output: github_document
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mosaic)
library(FNN)
sclass = read.csv("data/sclass.csv")

rmse = function(y, ypred) {
  sqrt(mean(data.matrix((y-ypred)^2)))
}
```

## GitHub Documents

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.

## Including Code


```{r sclass_350, echo=FALSE}
# Focus on 2 trim levels: 350 and 65 AMG
sclass350 = subset(sclass, trim == '350')
dim(sclass350)

N = nrow(sclass350)
N_train = floor(0.8*N)
N_test = N - N_train
train_ind = sample.int(N, N_train, replace=FALSE)

train = sclass350[train_ind,]
test = sclass350[-train_ind,]
test = arrange(test, mileage)

X_train = select(train, mileage)
y_train = select(train, price)
X_test = select(test, mileage)
y_test = select(test, price)


# KNN 250


knn250 = knn.reg(train = X_train, test = X_test, y = y_train, k=250)
ypred_knn250 = knn250$pred

knn3 = knn.reg(train = X_train, test = X_test, y = y_train, k=3)
ypred_knn3 = knn3$pred

knn5 = knn.reg(train = X_train, test = X_test, y = y_train, k=5)
ypred_knn5 = knn5$pred
knn10 = knn.reg(train = X_train, test = X_test, y = y_train, k=10)
ypred_knn10 = knn10$pred
knn20 = knn.reg(train = X_train, test = X_test, y = y_train, k=20)
ypred_knn20 = knn20$pred
knn50 = knn.reg(train = X_train, test = X_test, y = y_train, k=50)
ypred_knn50 = knn50$pred
knn100 = knn.reg(train = X_train, test = X_test, y = y_train, k=100)
ypred_knn100 = knn100$pred

test$ypred_knn250 = ypred_knn250

test$ypred_knn3 = ypred_knn3
test$ypred_knn5 = ypred_knn5
test$ypred_knn10 = ypred_knn10
test$ypred_knn20 = ypred_knn20
test$ypred_knn50 = ypred_knn50
test$ypred_knn100 = ypred_knn100

p_test_3 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn3), color='red')

p_test_3
rmse(y_test, ypred_knn3)

p_test_5 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn5), color='red')

p_test_5
rmse(y_test, ypred_knn5)

p_test_10 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn10), color='red')

p_test_10
rmse(y_test, ypred_knn10)

p_test_20 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn20), color='red')

p_test_20
rmse(y_test, ypred_knn20)

p_test_50 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn50), color='red')

p_test_50
rmse(y_test, ypred_knn50)

p_test_100 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn100), color='red')

p_test_100
rmse(y_test, ypred_knn100)

p_test_250 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn250), color='red')

p_test_250
rmse(y_test, ypred_knn250)

kframe <- data.frame("K" = c(), "RMEAN" =c())
i <- 3
while (i <= 250) {
  d = data.frame("K" = i, "RMEAN" = rmse(y_test, knn.reg(train = X_train, test = X_test, y = y_train, k=i)$pred))
  
  kframe = rbind(kframe, d)
  i = i + 1

}

k_vs_rmean = ggplot(data = kframe) + 
  geom_point(mapping = aes(x = K, y = RMEAN), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = K, y = RMEAN), color='red')
k_vs_rmean

print(min(kframe$RMEAN))

```

# sclass_65


```{r sclass_65, echo=FALSE}
# Focus on 2 trim levels: 350 and 65 AMG
sclass65 = subset(sclass, trim == '65 AMG')
dim(sclass65)

N = nrow(sclass65)
N_train = floor(0.8*N)
N_test = N - N_train
train_ind = sample.int(N, N_train, replace=FALSE)

train = sclass65[train_ind,]
test = sclass65[-train_ind,]
test = arrange(test, mileage)
train = arrange(train, mileage)

X_train = select(train, mileage)
y_train = select(train, price)
X_test = select(test, mileage)
y_test = select(test, price)

knn200 = knn.reg(train = X_train, test = X_test, y = y_train, k=200)
ypred_knn200 = knn200$pred

knn3 = knn.reg(train = X_train, test = X_test, y = y_train, k=3)
ypred_knn3 = knn3$pred

knn5 = knn.reg(train = X_train, test = X_test, y = y_train, k=5)
ypred_knn5 = knn5$pred
knn10 = knn.reg(train = X_train, test = X_test, y = y_train, k=10)
ypred_knn10 = knn10$pred
knn20 = knn.reg(train = X_train, test = X_test, y = y_train, k=20)
ypred_knn20 = knn20$pred
knn50 = knn.reg(train = X_train, test = X_test, y = y_train, k=50)
ypred_knn50 = knn50$pred
knn100 = knn.reg(train = X_train, test = X_test, y = y_train, k=100)
ypred_knn100 = knn100$pred

test$ypred_knn200 = ypred_knn200

test$ypred_knn3 = ypred_knn3
test$ypred_knn5 = ypred_knn5
test$ypred_knn10 = ypred_knn10
test$ypred_knn20 = ypred_knn20
test$ypred_knn50 = ypred_knn50
test$ypred_knn100 = ypred_knn100

p_test_3 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn3), color='red')

p_test_3
rmse(y_test, ypred_knn3)

p_test_5 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn5), color='red')

p_test_5
rmse(y_test, ypred_knn5)

p_test_10 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn10), color='red')

p_test_10
rmse(y_test, ypred_knn10)

p_test_20 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn20), color='red')

p_test_20
rmse(y_test, ypred_knn20)

p_test_50 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn50), color='red')

p_test_50
rmse(y_test, ypred_knn50)

p_test_100 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn100), color='red')

p_test_100
rmse(y_test, ypred_knn100)

p_test_200 = ggplot(data = test) + 
  geom_point(mapping = aes(x = mileage, y = price), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = mileage, y = ypred_knn200), color='red')

p_test_200
rmse(y_test, ypred_knn200)



kframe <- data.frame("K" = c(), "RMEAN" =c())
i <- 3
while (i <= 200) {
  d = data.frame("K" = i, "RMEAN" = rmse(y_test, knn.reg(train = X_train, test = X_test, y = y_train, k=i)$pred))
  kframe = rbind(kframe, d)
  i = i + 1
}
k_vs_rmean = ggplot(data = kframe) + 
  geom_point(mapping = aes(x = K, y = RMEAN), color='lightgrey') + 
  theme_bw(base_size=18) + geom_path(aes(x = K, y = RMEAN), color='red')
k_vs_rmean


print(min(kframe$RMEAN))
```


